### ISSUE TITLE
Reorganization / Task list

### ISSUE THREAD

**Issue by vismate** [AMIOL7/ELME#42]
As the rush of the final week of our project swiftly approaches I feel we need to reorganize ourselves to remain productive. 

Since @AMIOL7 fell ill the rest of us need to take over his work too. The following tasks must be worked on and completed: 

**Task group 1:**

Model:
- [x] running the simulation (updating from start nodes)
- [ ] serializing graph (generate truth table)
- [ ] deserialize graph (logic node based on truth table)

View:
- [x] #49
- [ ] saving and loading user created nodes
- [x] display newly implemented nodes in side menu

**Task group 2:**
- [x] exluding view code from code coverage analysis (as we only test the model)
- [x] continous deployment
- [x] package artifacts, so they are easily runnable on targeted platforms.
- [x] configure CD to leave previous versions available
- [x] clean up CI perhaps?

I'd like to make the initiative and assign @pszi and myself to **Task group 1** and @bgdxqi and myself to **Task group 2**.

If you have other recommendations please share. ~~Once we all agreed upon tasks we can close this issue.~~
We should use this issue _(alongside dedicated issues of course)_ to keep track of our progress.

Ps.: When @AMIOL7 feels better he may join any task he wishes.

**Comment by pszi** [comment]
@vismate If you need to work with the model, I'd suggest we separate **Task group 1**, and you only take over in my part in case I will be unable to finish the view in time, but I think 
> * display terminating nodes

and
> * display newly implemented nodes in side menu

I can very simply get done in the course of an afternoon.

As for
> * saving and loading user created nodes

if you know how to initiate (de)serialization of the working graph, you could have a crack at that, also if we want saved graphs to be able to be dragged in as nodes, you can look up the API docs on how to make Menus have dynamic content, and if you have a solution, feel free to share as I would like to be included, or at least informed at that.

**Comment by vismate** [comment]
I think we should use the task listing above to keep track of our progress.
**Also, I've implemented whats needed for our final assignment!!**

**Comment by AMIOL7** [comment]
@vismate is deserialization is really needed? If the file will contain truth table, wouldn't it be better to directly access it in simulation loop?

**Comment by AMIOL7** [comment]
Also, wouldn't it be better, if release is created only if at least unit tests are successful?

**Comment by vismate** [comment]
> @vismate is deserialization is really needed? If the file will contain truth table, wouldn't it be better to directly access it in simulation loop?

What I mean by deserialization here is to load that truth table and store it in memory. I don't think reading a file on each update would be appropriate. 

Also, the savefile would also store port labels which need to be loaded to display them.

**Comment by vismate** [comment]
> Also, wouldn't it be better, if release is created only if at least unit tests are successful?

The release job depends on unit tests. I believe this means unit tests must not fail in order to create a new release.

Correct me if thats not correct.

**Comment by AMIOL7** [comment]
> > Also, wouldn't it be better, if release is created only if at least unit tests are successful?
> 
> The release job depends on unit tests. I believe this means unit tests must not fail in order to create a new release.
> 
> Correct me if thats not correct.

Yes, that is correct.

**Comment by AMIOL7** [comment]
Sorry, my bad. Did not see a "needs" line of code in your commit

**Comment by AMIOL7** [comment]
@vismate I think we do not need to remove view code from sonarqube. We still need to check that part of code for code coverage, even if view code is not part of unit tests

**Comment by AMIOL7** [comment]
I have taken a look at the pipeline, there is nothing to fix or improve

**Comment by AMIOL7** [comment]
@vismate When are you going to submit the last assignment?

**Comment by vismate** [comment]
> @vismate When are you going to submit the last assignment?

After finishing the required documentation. I'll be done with it later today.
